In [96]:
import pandas as pd
import numpy as np

In [97]:
df = pd.read_csv('../data/nhpc_data.csv')

In [98]:
df.rename(columns={'Unnamed: 0': 'Date'}, inplace=True)
df.head()

         Date      Close       High        Low       Open    Volume
0  2023-03-06  37.832508  38.542755  37.074912  37.832508  11198659
1  2023-03-08  39.442402  39.584449  37.785158  37.785158  16875862
2  2023-03-09  38.637447  39.679145  38.400698  39.679145   5386529
3  2023-03-10  38.874199  39.158297  37.785155  38.353352   5220866
4  2023-03-13  38.116600  38.968898  37.785153  38.826847   6647383

In [99]:
df['Date'] = pd.to_datetime(df['Date'])
df.sort_values('Date', inplace=True)
df.reset_index(drop = True, inplace=True)

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    700 non-null    datetime64[ns]
 1   Close   700 non-null    float64
 2   High    700 non-null    float64
 3   Low     700 non-null    float64
 4   Open    700 non-null    float64
 5   Volume  700 non-null    int64
dtypes: datetime64[ns](1), float64(4), int64(1)
memory usage: 32.9 KB

In [101]:
print(df.head(), '\n',df.shape)

        Date      Close       High        Low       Open    Volume
0 2023-03-06  37.832508  38.542755  37.074912  37.832508  11198659
1 2023-03-08  39.442402  39.584449  37.785158  37.785158  16875862
2 2023-03-09  38.637447  39.679145  38.400698  39.679145   5386529
3 2023-03-10  38.874199  39.158297  37.785155  38.353352   5220866
4 2023-03-13  38.116600  38.968898  37.785153  38.826847   6647383
 (700, 6)

In [102]:
df.head(6)

        Date      Close       High        Low       Open    Volume
0 2023-03-06  37.832508  38.542755  37.074912  37.832508  11198659
1 2023-03-08  39.442402  39.584449  37.785158  37.785158  16875862
2 2023-03-09  38.637447  39.679145  38.400698  39.679145   5386529
3 2023-03-10  38.874199  39.158297  37.785155  38.353352   5220866
4 2023-03-13  38.116600  38.968898  37.785153  38.826847   6647383
5 2023-03-14  38.069252  38.590099  37.785154  38.116601   5564064

In [103]:
target_col = "Close"
feature_cols = ["Open", "High", "Low", "Volume"]

In [104]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, InputLayer
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError
from tensorflow.keras.metrics import RootMeanSquaredError
from tensorflow.keras.callbacks import ModelCheckpoint
from tensorflow.keras.models import load_model

In [105]:
WINDOW_SIZE = 2

In [106]:
def data_to_input_and_output(df, feature_cols, target_col):
    X = []
    y = []

    for i in range(len(df) - WINDOW_SIZE):
        # past WINDOW_SIZE rows, all features
        X.append(df[feature_cols].iloc[i:i+WINDOW_SIZE].values)

        # next step target
        y.append(df[target_col].iloc[i+WINDOW_SIZE])

    return np.array(X), np.array(y)

In [107]:
train_input, train_output = data_to_input_and_output(df, feature_cols=feature_cols, target_col=target_col)

In [108]:
print(train_input.shape, train_output.shape)

(698, 2, 4) (698,)

In [109]:
train_input[0]

array([[3.78325081e+01, 3.85427554e+01, 3.70749117e+01, 1.11986590e+07],
       [3.77851582e+01, 3.95844492e+01, 3.77851582e+01, 1.68758620e+07]])

In [110]:
train_output[0]

38.63744735717773

In [111]:
def train_neural_network(X, y, epochs=7, learning_rate=0.005):

    model = Sequential()
    model.add(InputLayer((WINDOW_SIZE, 4)))
    model.add(LSTM(64))
    model.add(Dense(8, 'relu'))
    model.add(Dense(1, 'linear'))

    check_point = ModelCheckpoint('model.h5', save_best_only=True, monitor='loss')
    model.compile(loss=MeanSquaredError(), optimizer=Adam(learning_rate=learning_rate), metrics=[RootMeanSquaredError()])

    model.fit(X, y, epochs=epochs, callbacks=[check_point])
    return model

In [114]:
model = train_neural_network(train_input, train_output, epochs=100, learning_rate=0.005)

Epoch 1/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 25s 1s/step - loss: 5114.1831 - root_mean_squared_error: 71.5135

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 5604.6562 - root_mean_squared_error: 74.8643
Epoch 2/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - loss: 4711.7598 - root_mean_squared_error: 68.6423

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 5245.3408 - root_mean_squared_error: 72.4247
Epoch 3/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 4414.3838 - root_mean_squared_error: 66.4408

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 4708.7861 - root_mean_squared_error: 68.6206
Epoch 4/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 4049.0562 - root_mean_squared_error: 63.6322

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3901.1228 - root_mean_squared_error: 62.4590
Epoch 5/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 3434.1687 - root_mean_squared_error: 58.6018

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 2863.0017 - root_mean_squared_error: 53.5070
Epoch 6/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 2072.5078 - root_mean_squared_error: 45.5248

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1838.1057 - root_mean_squared_error: 42.8731
Epoch 7/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 1341.2133 - root_mean_squared_error: 36.6226

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1061.0402 - root_mean_squared_error: 32.5736
Epoch 8/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 893.0018 - root_mean_squared_error: 29.8831

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 602.4322 - root_mean_squared_error: 24.5445
Epoch 9/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 548.9841 - root_mean_squared_error: 23.4304

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 422.3473 - root_mean_squared_error: 20.5511
Epoch 10/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 286.4663 - root_mean_squared_error: 16.9253

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 372.5540 - root_mean_squared_error: 19.3017
Epoch 11/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step - loss: 381.4169 - root_mean_squared_error: 19.5299

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 362.4551 - root_mean_squared_error: 19.0383
Epoch 12/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 355.4791 - root_mean_squared_error: 18.8509

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 361.6523 - root_mean_squared_error: 19.0172
Epoch 13/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 341.2637 - root_mean_squared_error: 18.4733

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 361.4565 - root_mean_squared_error: 19.0120
Epoch 14/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step - loss: 354.8332 - root_mean_squared_error: 18.8370

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 361.3947 - root_mean_squared_error: 19.0104
Epoch 15/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5749 - root_mean_squared_error: 19.0151
Epoch 16/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: 308.6183 - root_mean_squared_error: 17.5675

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 361.3164 - root_mean_squared_error: 19.0083
Epoch 17/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.7950 - root_mean_squared_error: 19.0209
Epoch 18/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4627 - root_mean_squared_error: 19.0122
Epoch 19/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4335 - root_mean_squared_error: 19.0114
Epoch 20/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 476.8698 - root_mean_squared_error: 21.8373

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 361.2799 - root_mean_squared_error: 19.0074
Epoch 21/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 361.4669 - root_mean_squared_error: 19.0123
Epoch 22/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8261 - root_mean_squared_error: 19.0217
Epoch 23/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3012 - root_mean_squared_error: 19.0079
Epoch 24/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3327 - root_mean_squared_error: 19.0088
Epoch 25/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 361.3529 - root_mean_squared_error: 19.0093
Epoch 26/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 351.9971 - root_mean_squared_error: 18.7616

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 361.2741 - root_mean_squared_error: 19.0072
Epoch 27/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4949 - root_mean_squared_error: 19.0130
Epoch 28/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3597 - root_mean_squared_error: 19.0095
Epoch 29/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4887 - root_mean_squared_error: 19.0129
Epoch 30/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4813 - root_mean_squared_error: 19.0127
Epoch 31/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8412 - root_mean_squared_error: 19.0221
Epoch 32/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8004 - root_mean_squared_error: 19.0211
Epoch 33/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.1620 - root_mean_squared_error: 19.0306
Epoch 34/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.9678 - root_mean_squared_error: 19.0255
Epoch 35/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 361.4934 - root_mean_squared_error: 19.0130
Epoch 36/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3063 - root_mean_squared_error: 19.0081
Epoch 37/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4078 - root_mean_squared_error: 19.0107
Epoch 38/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4767 - root_mean_squared_error: 19.0125
Epoch 39/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3413 - root_mean_squared_error: 19.0090
Epoch 40/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8703 - root_mean_squared_error: 19.0229
Epoch 41/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3800 - root_mean_squared_error: 19.0100
Epoch 42/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4697 - root_mean_squared_error: 19.0124
Epoch 43/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3749 - root_mean_squared_error: 19.0099
Epoch 44/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5213 - root_mean_squared_error: 19.0137
Epoch 45/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5059 - root_mean_squared_error: 19.0133
Epoch 46/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.7228 - root_mean_squared_error: 19.0190
Epoch 47/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4148 - root_mean_squared_error: 19.0109
Epoch 48/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 361.5823 - root_mean_squared_error: 19.0153
Epoch 49/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3152 - root_mean_squared_error: 19.0083
Epoch 50/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3029 - root_mean_squared_error: 19.0080
Epoch 51/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5971 - root_mean_squared_error: 19.0157
Epoch 52/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5257 - root_mean_squared_error: 19.0138
Epoch 53/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.4324 - root_mean_squared_error: 19.0377
Epoch 54/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.6973 - root_mean_squared_error: 19.0183
Epoch 55/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4944 - root_mean_squared_error: 19.0130
Epoch 56/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.6175 - root_mean_squared_error: 19.0162
Epoch 57/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.9773 - root_mean_squared_error: 19.0257
Epoch 58/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5163 - root_mean_squared_error: 19.0136
Epoch 59/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.7578 - root_mean_squared_error: 19.0199
Epoch 60/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4251 - root_mean_squared_error: 19.0112
Epoch 61/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.6217 - root_mean_squared_error: 19.0164
Epoch 62/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4905 - root_mean_squared_error: 19.0129
Epoch 63/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4372 - root_mean_squared_error: 19.0115
Epoch 64/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 361.5789 - root_mean_squared_error: 19.0152
Epoch 65/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3756 - root_mean_squared_error: 19.0099
Epoch 66/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4751 - root_mean_squared_error: 19.0125
Epoch 67/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.6511 - root_mean_squared_error: 19.0171
Epoch 68/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.9979 - root_mean_squared_error: 19.0262
Epoch 69/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4572 - root_mean_squared_error: 19.0120
Epoch 70/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5837 - root_mean_squared_error: 19.0154
Epoch 71/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8463 - root_mean_squared_error: 19.0223
Epoch 72/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.3713 - root_mean_squared_error: 19.0361
Epoch 73/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 363.0273 - root_mean_squared_error: 19.0533
Epoch 74/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.9545 - root_mean_squared_error: 19.0514
Epoch 75/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.7585 - root_mean_squared_error: 19.0199
Epoch 76/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.5201 - root_mean_squared_error: 19.0400
Epoch 77/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8564 - root_mean_squared_error: 19.0225
Epoch 78/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5382 - root_mean_squared_error: 19.0142
Epoch 79/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 361.8769 - root_mean_squared_error: 19.0231
Epoch 80/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3662 - root_mean_squared_error: 19.0096
Epoch 81/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3835 - root_mean_squared_error: 19.0101
Epoch 82/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4965 - root_mean_squared_error: 19.0131
Epoch 83/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.5058 - root_mean_squared_error: 19.0133
Epoch 84/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 361.5968 - root_mean_squared_error: 19.0157
Epoch 85/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.0285 - root_mean_squared_error: 19.0270
Epoch 86/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.0154 - root_mean_squared_error: 19.0267
Epoch 87/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.3171 - root_mean_squared_error: 19.0083
Epoch 88/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.7587 - root_mean_squared_error: 19.0200
Epoch 89/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.8338 - root_mean_squared_error: 19.0482
Epoch 90/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8815 - root_mean_squared_error: 19.0232
Epoch 91/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.6250 - root_mean_squared_error: 19.0427
Epoch 92/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8386 - root_mean_squared_error: 19.0221
Epoch 93/100
 1/22 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 426.3900 - root_mean_squared_error: 20.6492

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 361.2121 - root_mean_squared_error: 19.0056
Epoch 94/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.6150 - root_mean_squared_error: 19.0162
Epoch 95/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.6309 - root_mean_squared_error: 19.0166
Epoch 96/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.1812 - root_mean_squared_error: 19.0311
Epoch 97/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 362.2881 - root_mean_squared_error: 19.0339
Epoch 98/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.4363 - root_mean_squared_error: 19.0115
Epoch 99/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.8733 - root_mean_squared_error: 19.0230
Epoch 100/100
22/22 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 361.6592 - root_mean_squared_error: 19.0173